#!/bin/bash
rm -rf pathway_results
mkdir pathway_results
cd pathway_results
cp ../${1} .
../ecsearch 1.1.1.28 ${1} | sort -k2 -g -t, > 1.1.1.28 &
../ecsearch 1.1.1.27 ${1} | sort -k2 -g -t, > 1.1.1.27 &
../ecsearch 1.1.99.7 ${1} | sort -k2 -g -t, > 1.1.99.7 &
../ecsearch 1.2.7.1 ${1} | sort -k2 -g -t, > 1.2.7.1 &
../ecsearch 2.3.1.8 ${1} | sort -k2 -g -t, > 2.3.1.8 &
../ecsearch 3.6.1.7 ${1} | sort -k2 -g -t, > 3.6.1.7 &
../ecsearch 6.4.1.1 ${1} | sort -k2 -g -t, > 6.4.1.1 &
../ecsearch 1.1.1.37 ${1} | sort -k2 -g -t, > 1.1.1.37 &
../ecsearch 4.2.1.2 ${1} | sort -k2 -g -t, > 4.2.1.2 &
../ecsearch 1.3.5.4 ${1} | sort -k2 -g -t, > 1.3.5.4 &
../ecsearch 1.3.5.1 ${1} | sort -k2 -g -t, > 1.3.5.1 &
../ecsearch 2.8.3.- ${1} | sort -k2 -g -t, > 2.8.3.- &
../ecsearch 5.4.99.2 ${1} | sort -k2 -g -t, > 5.4.99.2 &
../ecsearch 4.1.1.41 ${1} | sort -k2 -g -t, > 4.1.1.41 &
../ecsearch 6.4.1.3 ${1} | sort -k2 -g -t, > 6.4.1.3 &
../ecsearch 2.1.3.1 ${1} | sort -k2 -g -t, > 2.1.3.1 &
